columns:
  - field: price
    displayName: "Price"
    internalName: "price"
    inSaveForm: true
    inEditForm: true
    inTable: true
    required: true
    min: 1
    max: 99999999.99

  - field: operator
    displayName: "Operator"
    internalName: "operator"
    strValues: ["<=", ">="]
    inSaveForm: true
    inEditForm: true
    inTable: true
    required: true

  - field: amountOfNotifications
    displayName: "How many times notify?"
    internalName: "amountOfNotifications"
    inSaveForm: true
    inEditForm: true
    inTable: true
    required: true
    min: 1
    max: 100

  - field: checkIntervalMinutes
    displayName: "How Often Check (m)?"
    internalName: "checkIntervalMinutes"
    inSaveForm: true
    inEditForm: true
    inTable: true
    required: true
    min: 1
    max: 1440  # max. 24h

  - field: anotherNotificationEachPercentage
    displayName: "How many % change to notify again?"
    internalName: "anotherNotificationEachPercentage"
    inSaveForm: true
    inEditForm: true
    inTable: true
    required: true
    min: 1
    max: 100